### ISSUE TITLE
About FFOE VQA why using teacher model

### ISSUE THREAD

**Issue by alice-cool** [aioz-ai/ICCV19_VQA-CTI#14]
Dear scholar,
I think FFOE VQA's answer is fixed about 3094 answer label. It also uses them in test phrase, it doesn't matter if it is training or testing. 

Because I think in training pharse we view the VQA2.0 as multi-label classification.  Similary , we also should get answer label from the same set of training test, that is the answer id is sharing with the answer id in test phrase.

**Comment by Gazeal** [comment]
Well, in the paper, we view the VQA  task as a multi-label classification. The class labels are identified through the statistical process in the train set. Specifically, 3094 answer labels are the ground-truth answers that appear in more than 9 V-Q pairs (in the train set). This means that if a V-Q pair in the test set has an answer that is out of our label set, we should consider that the model always outputs the wrong prediction, rather than ignore that V-Q pair. By indexing the labels in both the train/test phases, we can speed up the time used for checking if our answers are correct or not. Overall, it is still similar if we check the exact match between the predicted answers and the ground-truth ones during testing. P/s: in our benchmarking sections, for a fair comparison, the preprocessing for class labels of all VQA multi-label classification-based methods is the same.
